### ISSUE TITLE
mismatch between webpage, and script.

### ISSUE THREAD

**Issue by FrankRizzo890** [nelenkov/verity#2]
On your webpage here: http://nelenkov.blogspot.com/search?q=verity You show this:

 veritysetup --debug --hash-offset 838893568 --data-blocks 204800 format \
/dev/block/mmcblk0p21 /dev/block/mmcblk0p21
...
 Updating VERITY header of size 512 on device /dev/block/mmcblk0p21, offset 838893568.
VERITY header information for /dev/block/mmcblk0p21
UUID:                   0dd970aa-3150-4c68-abcd-0b8286e6000
Hash type:              1
Data blocks:            204800
Data block size:        4096
Hash block size:        4096
Hash algorithm:         sha256
Salt:                   1f951588516c7e3eec3ba10796aa17935c0c917475f8992353ef2ba5c3f47bcb
Root hash:              5f061f591b51bf541ab9d89652ec543ba253f2ed9c8521ac61f1208267c3bfb1

You then mention running gentable.py.  You then show your table:

1 /dev/block/mmcblk0p21 /dev/block/mmcblk0p21 4096 4096 204800 204809 sha256 \
1f951588516c7e3eec3ba10796aa17935c0c917475f8992353ef2ba5c3f47bcb \
5f061f591b51bf541ab9d89652ec543ba253f2ed9c8521ac61f1208267c3bfb1

Which shows that the SALT is 1st.  And THEN the root hash.  But, looking at the source for gentable.py, you have this:

table = fmt % (DATA_DEV, hash_dev, data_block_size, hash_block_size, num_blocks, hash_offset, ROOT_DIGEST, SALT)

Which one is correct?

**Comment by nelenkov** [comment]
The source code is correct, because it actually works :) 

Also see the linked dm-verity documentation at https://gitlab.com/cryptsetup/cryptsetup/wikis/DMVerity

Mapping table:
`<ver> <data_dev> <hash_dev> <data_blk_size> <hash_blk_size> <#blocks> <hash_start> <alg> <digest> <salt>`

**Comment by nelenkov** [comment]
BTW, if you are working with Android 5.0 or later source code, all of this is already available in the build system, you just need to add something like this to your `device.mk`:

`PRODUCT_SYSTEM_VERITY_PARTITION := /dev/block/platform/msm_sdcc.1/by-name/system
$(call inherit-product, build/target/product/verity.mk)`

And then change `fstab` accordingly.
